package py.sistienda.core.security;

public enum Permiso {
    CATALOGO_VER,
    CATALOGO_GESTIONAR,
    COSTOS_VER,
    STOCK_GESTIONAR,
    ETIQUETAS_IMPRIMIR,
    CAJA_OPERAR,
    CAJA_MOVIMIENTOS,
    ARQUEO_VER,
    REPORTES_VER,
    COMPRAS_GESTIONAR,
    CONFIGURACION_GESTIONAR,
    USUARIOS_GESTIONAR
}
